### ISSUE TITLE
Customized landing page not working

### ISSUE THREAD

**Issue by dagrammy** [event-catalog/eventcatalog#936] opened 2024-11-07 08:49 UTC
### I tried this:

I tried to customize a landing page like described here:
https://www.eventcatalog.dev/docs/development/guides/custom-pages/introduction#changing-the-default-landing-page

### This happened:

The default landing page is shown.

### I expected this:

I expected the customized landing page to be shown while browsing http://localhost:3000/ in development mode.

### Anything else?

Reproduce by:

Create a new catalog
`npx @eventcatalog/create-eventcatalog@latest my-catalog` 

Modify `pages/index.md`

Run `npm run dev` and browse to http://localhost:3000/

### EventCatalog Version

@eventcatalog/core@2.12.1

### Node.js Version

v23.1.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment] 2024-11-07 11:02
Thanks @dagrammy , I will pick this up, I know @XaaXaaX has done some work around this. 

I did some refactoring to the UI last week, and looks like it was removed.

**Comment by XaaXaaX** [comment] 2024-11-07 11:09
> Thanks @dagrammy , I will pick this up, I know @XaaXaaX has done some work around this.
> 
> I did some refactoring to the UI last week, and looks like it was removed.

Hey @dagrammy , yes this functionality got in a regression behind refactoring, i have a PR to manage it 

@boyney123  here the PR i did https://github.com/event-catalog/eventcatalog/pull/919

**Comment by boyney123** [comment] 2024-11-07 16:52
Should be fixed in `@eventcatalog/core@2.12.2`

**Closed** 2024-11-07 16:55 UTC
Labels: bug, ready-for-implementation

**Comment by dagrammy** [comment] 2024-11-08 07:23
Thank you @boyney123  and @XaaXaaX  for the quick fix. 🙂 

I have one more question: It is not possible to customize the home page, is it?

![image](https://github.com/user-attachments/assets/582c0e11-2c62-4d41-86c5-a1d4d31843e4)

**Comment by boyney123** [comment] 2024-11-08 11:34
Not at the moment @dagrammy , but might be part of this https://discord.com/channels/918092420338569216/1304042250589966376

 will keep it in mind! Thanks

**Comment by seanhagen** [comment] 2025-02-07 23:47
Is there any chance that stuff in Discord can be mirrored in the issues or wiki in this repo? Using Discord makes it impossible to find things naturally by searching either with a search engine or directly in GitHub. 

There's also the possibility of Discord being blocked by company IT security policies, potentially locking folks out of being able to participate when thoughts & ideas are fresh in their mind.
