### ISSUE TITLE
Mermaid diagrams not working in domains

### ISSUE THREAD

**Issue by RenugaParamalingam** [event-catalog/eventcatalog#376] opened 2023-04-05 02:54 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

If mermaid diagrams is added under services/events, it is working as expected. But not in the index.md file under domains.

### Steps to reproduce

Step 1: Download and install EventCatalog per the instructions
Step 2:  Add the following code in the file named index.md under domains directory.
```
<Mermaid title="Event Rules & Targets" charts={[`flowchart LR 
Start --> Stop`]} />
```
Step 3: Run the EventCatalog

### Expected behavior

Mermaid diagram should show up.

### Actual behavior

Mermaid diagram is not available.
And found the following error getting logged.
``` 
Component Mermaid was not imported, exported, or provided by MDXProvider as global scope
```

### Your environment

- EventCatalog version used: 0.6.8
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js v14.21.3
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac 13.2.1

**Comment by stanipetrosyan** [comment] 2023-08-02 11:08
Hi, I think this is not a bug but a feature, because reading docs in website [https://www.eventcatalog.dev/docs/components/domains](url), there's no Mermaid support. I need too this function, so if @boyney123 agrees I can try to create a pull request for this.

**Comment by boyney123** [comment] 2023-08-11 06:48
Hey,

Yeah no real reason why this is not supported, thanks for the PR!

**Comment by Jackfr0stt** [comment] 2023-12-11 11:30
Any updates on the merging of this PR?

**Comment by stanipetrosyan** [comment] 2023-12-11 12:15
I'm waiting approve from @boyney123

**Comment by boyney123** [comment] 2024-07-04 16:18
Thanks for raising this issue. 

EventCatalog v2 is coming out very soon, so going to close this as I believe it’s no longer an issue in the new version. 

If you still experience this issue please raise a new issue. 

Thank you!

**Closed by boyney123** 2024-07-04 16:18 UTC
Labels: bug
