### ISSUE TITLE
CSS not loading when deploying event catalog as github pages

### ISSUE THREAD

**Issue by uditnarayan** [event-catalog/eventcatalog#639] opened 2024-07-24 14:09 UTC
So I created an event catalog and setup a github action pipeline to build and deploy the catalog to github pages:

```
name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build 🔧 
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
```

The deploy action here commits the build into a new branch gh-pages so that I can use the root of the branch as root of my static website. The event catalog loads like this:

![image](https://github.com/user-attachments/assets/bfd292d7-6dfa-49bc-814f-364fb6777dcf)

Looks like the files hosted inside _astro folder are not loaded, while it loads everything else correctly.

**Comment by uditnarayan** [comment] 2024-07-25 08:04
Actually the bigger problem is that event though files are present but still we receive 404

<img width="674" alt="image" src="https://github.com/user-attachments/assets/601c125b-2c9f-487d-a34c-0eec2524787b">

**Comment by carlosallexandre** [comment] 2024-07-26 14:42
Hey @uditnarayan, is everything ok?

I made two simple example to publish for github pages:
1. [Publishing from a custom Github Action workflow](https://github.com/carlosallexandre/eventcatalog-sample-with-github-actions)
2. [Publishing from a branch](https://github.com/carlosallexandre/eventcatalog-sample)

> [!NOTE]
> *Publishing from a branch* is not fully working. I'm still investiganting.

Let us know if this works for you.

**Comment by boyney123** [comment] 2024-08-05 08:59
Going to close this for now, if the issue is still there can you re-open please?

**Closed by boyney123** 2024-08-05 08:59 UTC
